environment_version = "2026.1-dev"

[ubuntu]
version = "26.04"

[supported]
architectures = ["amd64", "arm64"]

[apt_mirror]
name = "阿里云"
amd64_uri = "https://mirrors.aliyun.com/ubuntu/"
arm64_uri = "https://mirrors.aliyun.com/ubuntu-ports/"
